### ISSUE TITLE
certutil not installed

### ISSUE THREAD

**Issue by yanlinaung30** [cretz/mkcert#1]
I cannot install on Windows 10. It says certutil is not installed.
```
C:\Users\User Name\mkcert>mkcert -install
Created a new local CA at "C:\Users\User Name\AppData\Local\mkcert" 💥
The local CA is now installed in the system trust store! ⚡️
Warning: "certutil" is not available, so the CA can't be automatically installed in Firefox! ⚠️
Install "certutil" with "<certutil unsupported on Windows>" and re-run "mkcert -install" 👈
```

**Comment by cretz** [comment]
That's just a warning, not an error. The install completed successfully, it's just for Firefox it isn't installed. It's not an issue I wanted to tackle with this version, I just wanted to make sure to get in the OS's root store.

Expand the details at https://github.com/FiloSottile/mkcert/pull/46#issuecomment-409260718 to see the walkthrough which does just what you did and gets the FF warning, which is no prob.

**Comment by yanlinaung30** [comment]
@cretz Thanks for your reply! I will check it.
